### ISSUE TITLE
Error running config for nvim-lsp-installer

### ISSUE THREAD

**Issue by rafaelderolez** [CosmicNvim/CosmicNvim#2]
Error on launch after having run `PackerUpdate` & `PackerCompile`
```lua
~/.config/nvim/lua/cosmic/lsp/diagnostics.lua:5: attempt to index field 'diagnostic' (a nil value)
```

https://github.com/mattleong/CosmicNvim/blob/main/lua/cosmic/lsp/diagnostics.lua#L5

**Comment by mattleong** [comment]
@rafaelderolez What does `nvim --version` say? There's a strict requirement for 0.6+ (had added that note in the readme this morning)
