### ISSUE TITLE
Theme suggestions

### ISSUE THREAD

**Issue by mattleong** [CosmicNvim/CosmicNvim#25]
Hi all,

I've previously said that I wouldn't be implementing additional first class themes to CosmicNvim, however..... It seems that I've changed my mind and have just implemented a few additional color schemes that receive first-class treatment in CosmicNvim. 😇

My previous contention to adding in additional themes was that I wanted to ensure complexity within CosmicNvim stayed relatively sane. However, I feel like I've found a decent middle ground that allows easy addition of any color scheme you may want to provide first-class support for, (see: https://github.com/mattleong/CosmicNvim/tree/main/lua/cosmic/core/theme/integrated).

As you can see, the default list for themes is currently:

- [Catppuccino](https://github.com/Pocco81/Catppuccino.nvim)
- [Gruvbox](https://github.com/ellisonleao/gruvbox.nvim)
- [Nord](https://github.com/shaunsingh/nord.nvim)
- [Tokyonight](https://github.com/folke/tokyonight.nvim)

I would love suggestions for any additional themes that you'd like to see integrated into CosmicNvim! Thanks!

(See readme and updated example in `config/example/config.lua` to change your theme)

**Comment by undeadbydawn** [comment]
Gruvbox doesn't appear to be working properly. The rest are fine

**Comment by mattleong** [comment]
@undeadbydawn I fixed the notification warning for gruvbox. It didn't really affect anything other than being annoying but it's gone now. 

It looks solid to me!

**Comment by mattleong** [comment]
[Enfocado](https://www.reddit.com/r/vimporn/comments/qtimq3/comment/hkjy1bj/?utm_source=share&utm_medium=web2x&context=3)

**Comment by undeadbydawn** [comment]
[Dracula](https://github.com/dracula/vim) since it's everywhere else and feels odd not have have it here

A strong second for Enfocado Neon

**Comment by mattleong** [comment]
[Nightfly](https://github.com/EdenEast/nightfox.nvim)

Suggestion from [discord](https://discord.com/channels/901609359291854899/901609359803564074/912107567772209152)

**Comment by hsheikhali1** [comment]
> [Nightfly](https://github.com/EdenEast/nightfox.nvim)
> 
> Suggestion from [discord](https://discord.com/channels/901609359291854899/901609359803564074/912107567772209152) 
> 
> Edit: Added! Thanks @hsheikhali1!

Nightfox ;) and no problemo!

**Comment by mattleong** [comment]
@undeadbydawn Dracula has been added!

**Comment by wuelnerdotexe** [comment]
> ~[Enfocado](https://www.reddit.com/r/vimporn/comments/qtimq3/comment/hkjy1bj/?utm_source=share&utm_medium=web2x&context=3) suggested from reddit~
> 
> Added!

@mattleong thanks for added [Enfocado](https://wuelnerdotexe.github.io/enfocado). Cosmically focused !! 👁️

**Comment by undeadbydawn** [comment]
> @undeadbydawn Dracula has been added!

excellent.
In other good news I just figured out how to switch themes without breaking everything else.
Weirdly, it involved reading the instructions

**Comment by undeadbydawn** [comment]
Nice.
I still haven't figured out how to activate themes, though (at least without breaking things)
I'm assuming it's really obvious and I'm just completely failing to follow the instructions

**Comment by hsheikhali1** [comment]
> Nice.
> I still haven't figured out how to activate themes, though (at least without breaking things)
> I'm assuming it's really obvious and I'm just completely failing to follow the instructions

How are you setting your config? Cosmic is pretty cool in that you can create a `config.lua` and set the theme there plus other stuff. There should be an example under the `examples/` directory

**Comment by undeadbydawn** [comment]
> > Nice.
> > I still haven't figured out how to activate themes, though (at least without breaking things)
> > I'm assuming it's really obvious and I'm just completely failing to follow the instructions
> 
> How are you setting your config? Cosmic is pretty cool in that you can create a `config.lua` and set the theme there plus other stuff. There should be an example under the `examples/` directory

my config.lua consists exclusively of an attempt to switch themes. I have other commands in editor.lua that work perfectly
`config.theme = 'theme'` does literally nothing.
`theme = 'theme'` prompts a screen full of deletions.
as far as I can tell the examples/config.lua gives no other useful instructions

**Comment by mattleong** [comment]
> > > Nice.
> 
> > > I still haven't figured out how to activate themes, though (at least without breaking things)
> 
> > > I'm assuming it's really obvious and I'm just completely failing to follow the instructions
> 
> > 
> 
> > How are you setting your config? Cosmic is pretty cool in that you can create a `config.lua` and set the theme there plus other stuff. There should be an example under the `examples/` directory
> 
> 
> 
> my config.lua consists exclusively of an attempt to switch themes. I have other commands in editor.lua that work perfectly
> 
> `config.theme = 'theme'` does literally nothing.
> 
> `theme = 'theme'` prompts a screen full of deletions.
> 
> as far as I can tell the examples/config.lua gives no other useful instructions

What theme are you trying to set? Can you provide your config?

**Comment by undeadbydawn** [comment]
> 

This is my current config.lua,:
```
--config.theme = 'dracula'
config.theme = 'catppuccin'
-- config.theme = 'enfocado'
-- config.theme = 'gruvbox'
-- config.theme = 'nightfox'
-- config.theme = 'nord'
-- config.theme = 'onedark'
-- config.theme = 'rose-pine'
-- config.theme = 'tokyonight'
-- config.theme =
-- config.theme =
```

**Comment by undeadbydawn** [comment]
I mean.. it's painfully obvious I just don't know what I'm doing, so to be clear I am in no way complaining about things being difficult to do. I'm 100% certain it's really easy and I'm simply not seeing it

**Comment by mattleong** [comment]
> I mean.. it's painfully obvious I just don't know what I'm doing, so to be clear I am in no way complaining about things being difficult to do. I'm 100% certain it's really easy and I'm simply not seeing it

Are you running `:PackerSync` or `:CosmicReloadSync` after you change the setting?

**Comment by undeadbydawn** [comment]
Many, many times.
The only way I can get the theme to change is by adjusting line 9 of config/init.lua, which of course has to be changed back to run updates. Not a deal-breaker, but less than ideal. On the upside I like tokyonight enough to just keep it anyway

**Comment by mattleong** [comment]
> Many, many times.
> 
> The only way I can get the theme to change is by adjusting line 9 of config/init.lua, which of course has to be changed back to run updates. Not a deal-breaker, but less than ideal. On the upside I like tokyonight enough to just keep it anyway

Double check the example and make sure you're actually returning `config`

**Comment by undeadbydawn** [comment]
> > Many, many times.
> > The only way I can get the theme to change is by adjusting line 9 of config/init.lua, which of course has to be changed back to run updates. Not a deal-breaker, but less than ideal. On the upside I like tokyonight enough to just keep it anyway
> 
> Double check the example and make sure you're actually returning `config`

Ok, got it working with
```
local config = {}
config.theme = 'theme'
return config
```
which should have been obvious but really wasn't. TIL, etc
Also set enfocado to neon, which is really, _really_ nice, and fits my DE remarkably well

**Comment by undeadbydawn** [comment]
One more (probably final) question:
the Enfocado website shows colour borders around terminal windows, but not how to activate them.
Is it possible to do that with Cosmic? If so, how? I'm mostly using Konsole

**Comment by lttb** [comment]
Thanks for the great config! I believe it'd be great to support the [Github Theme](https://github.com/projekt0n/github-nvim-theme) out of the box too

**Comment by mattleong** [comment]
@lttb the github theme has been added :)

**Comment by vanarok** [comment]
I haven't found how to set the theme option(light/white), Is this feature not there yet?

**Comment by unr** [comment]
> [Dracula](https://github.com/dracula/vim) since it's everywhere else and feels odd not have have it here
> 
> A strong second for Enfocado Neon

Happy to see Dracula here, curious if there is any smart way to install Dracula Pro?

Or better suited to the project, a way to install a local theme yourself?
