### ISSUE TITLE
nvim-notify should load only after colorscheme has been fully loaded

### ISSUE THREAD

**Issue by undeadbydawn** [CosmicNvim/CosmicNvim#36]
Running 'gruvbox' I'm getting a consistent
```

Highlight group 'Normal' has no background highlight.

Please provide an RGB hex value or highlight group with a background value for 'background_colour' option

Defaulting to #000000
```

Enfocado no longer respects the

`vim.g.theme_option = 'neon'`
command,
and the standard variant gives
```

Opacity changes require termguicolors to be set.
Change to different animation stages or set termguicolors to disable this warning
```

tokyonight functions perfectly

finally, the command set I was previously given to change the dashboard colour

```
local highlight = require('cosmic.utils').highlight
highlight('DashboardHeader', 'None', 'Purple') 
```
no longer does anything at all

**Comment by mattleong** [comment]
> Running 'gruvbox' I'm getting a consistent
> ```
> Highlight group 'Normal' has no background highlight.
> Please provide an RGB hex value or highlight group with a background value for 'background_colour' option
> Defaulting to #000000
> ```

Hmm.. Think I've found a work around for this. 👍 

>Enfocado no longer respects the `vim.g.theme_option = 'neon'` command,

Works fine for me when placed in `lua/cosmic/config/editor.lua`

> and the standard variant gives
> ```
> Opacity changes require termguicolors to be set.
> Change to different animation stages or set termguicolors to disable this warning
> ```

Also believe I've found a fix for this 😄 

> finally, the command set I was previously given to change the dashboard colour... no longer does anything at all

Highlight helper moved somewhat recently... try this. 
```lua
local highlight = require('cosmic.theme.utils').highlight
```

**Comment by mattleong** [comment]
@undeadbydawn Sorry, pr auto closed the issue. Please let me know if you still see any issues!

**Comment by wuelnerdotexe** [comment]
> _"Enfocado no longer respects the vim.g.theme_option = 'neon' command, ..."_

@undeadbydawn hi, the variable to change the style of the **Enfocado** theme is `vim.g.enfocado_style = 'neon'` and you can modify it [here](https://github.com/CosmicNvim/CosmicNvim/blob/3be2d316fc41933617c2a5deb4cec4d0ff7e299a/lua/cosmic/theme/plugins.lua#L112).

That should work :)

**Comment by mattleong** [comment]
@wuelnerdotexe ah thanks for the clarification! I had copy and pasted from your repo to test and not from this issue. 😅

**Comment by wuelnerdotexe** [comment]
@mattleong no problem, I think I will also have to update the options for **Enfocado** here in **Cosmic**, because with the last commit my solution will no longer be needed 🙂

I'll send my PR in a moment...
