### ISSUE TITLE
File tree toggle not working

### ISSUE THREAD

**Issue by joshmlamb** [CosmicNvim/CosmicNvim#38]
I'm running into an issue toggling the file tree when first opening Neovim inside a project directory. Pressing `<C-n>` doesn't toggle the file tree, however, after manually running `:NvimTreeToggle` pressing `<C-n>` then toggles the file tree. I was wondering if this is an issue anyone else is facing?

Thank you for creating and releasing this configuration layer for Neovim, it's been a great experience so far.

**Comment by joshmlamb** [comment]
After remapping the `:NvimTreeToggle` command to `<leader>e`, I'm no onger having this issue.

**Comment by mattleong** [comment]
@joshmlamb Hi! Glad to hear you found suitable workaround. 

Can you tell me if you are using dashboard.nvim or not? I haven't seen similar issues myself.

**Comment by andrew-chon** [comment]
I'm also experiencing the same behavior as josh.  `<C-n>` doesn't work until the file tree is triggered by something else e.g. `:NvimTreeToggle` or pressing enter on the `File Manager` from the dashboard.

**Comment by mattleong** [comment]
@andrew-chon just pushed a fix that should fix this.. 

If it doesn't, let me know if you're running the default config setup or what custom settings you have so I can troubleshoot better.

**Comment by andrew-chon** [comment]
Hey @mattleong, I uninstalled per the instructions in the wiki and did a fresh install with default configs.  
Getting the same error as https://github.com/CosmicNvim/CosmicNvim/issues/40 and now the `<C-n>` doesn't toggle nvim-tree at all and just scrolls down the list of files.

**Comment by mattleong** [comment]
@andrew-chon Please post your custom settings if you have any
