### ISSUE TITLE
Errors on update. Running Gruvbox

### ISSUE THREAD

**Issue by undeadbydawn** [CosmicNvim/CosmicNvim#39]
`packer.nvim: Error running config for vim-notify:... ck/packer/start/lush.nvim/lua/lush/vivid/convert.lua:79: attempt to perform arithmetic on field 'h' (a nil value)`

`packer.nvim: Error running config for galaxyline.nvim: ...dawn/.config/nvim/lua/cosmic/plugins/galaxyline/init.lua:7: loop or previous error loading module 'cosmic.theme.colors`

**Comment by undeadbydawn** [comment]
follow up note to say this appears to be gruvbox specific. I've move back to Enfocado Neon and the issue vanished

**Comment by mattleong** [comment]
@undeadbydawn This issue should be resolved with https://github.com/CosmicNvim/CosmicNvim/pull/42 😄
