### ISSUE TITLE
on current build after :PackerSync

### ISSUE THREAD

**Issue by undeadbydawn** [CosmicNvim/CosmicNvim#40]
```
Error detected while processing /home/undeadbydawn/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/undeadbydawn/.config/nvim/init.lua:16: Error loading core...

/home/undeadbydawn/.config/nvim/lua/cosmic/init.lua:14: Error loading cosmic.core...

/home/undeadbydawn/.config/nvim/lua/cosmic/core/init.lua:14: Error loading cosmic.core.mappings...

...e/undeadbydawn/.config/nvim/lua/cosmic/core/mappings.lua:2: module 'cosmic.config.plugins' not found:
no field package.preload['cosmic.config.plugins']No cache entry
no file './cosmic/config/plugins.lua'
no file '/usr/share/luajit-2.0.5/cosmic/config/plugins.lua'
no file '/usr/local/share/lua/5.1/cosmic/config/plugins.lua'
no file '/usr/local/share/lua/5.1/cosmic/config/plugins/init.lua'
no file '/usr/share/lua/5.1/cosmic/config/plugins.lua'
no file '/usr/share/lua/5.1/cosmic/config/plugins/init.lua'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/cosmic/config/plugins.lua'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/share/lua/5.1/cosmic/config/plugins/init.lua'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/cosmic/config/plugins.lua'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/lib/luarocks/rocks-5.1/cosmic/config/plugins/init.lua'
no file './cosmic/config/plugins.so'
no file '/usr/local/lib/lua/5.1/cosmic/config/plugins.so'
no file '/usr/lib/lua/5.1/cosmic/config/plugins.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/cosmic/config/plugins.so'
no file './cosmic.so'
no file '/usr/local/lib/lua/5.1/cosmic.so'
no file '/usr/lib/lua/5.1/cosmic.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file '/home/undeadbydawn/.cache/nvim/packer_hererocks/2.0.5/lib/lua/5.1/cosmic.so'
stack traceback:
[C]: in function 'error'
/home/undeadbydawn/.config/nvim/init.lua:16: in main chunk
```

**Comment by mattleong** [comment]
@undeadbydawn Please run `:CosmicReloadSync` and see if the problem persists

**Comment by undeadbydawn** [comment]
> @undeadbydawn Please run `:CosmicReloadSync` and see if the problem persists

Problem persists

**Comment by mattleong** [comment]
@undeadbydawn Have you updated cosmic recently? 

Can you also share any custom settings you have set?

**Comment by maxime50** [comment]
I think this happen since https://github.com/CosmicNvim/CosmicNvim/commit/988b14ec9e04af0f9290ddd82a987ba7baffc81e and https://github.com/CosmicNvim/CosmicNvim/commit/80580b7f7bed29ffbf527bce29a58417a6bca511. Because

``` lua
local user_plugins = require('cosmic.config.plugins')
````
requires the file `cosmic.config.plugins` which is not always present. It's only inside the `example` folder by default if i'm correct.
Might be the same issue as https://github.com/CosmicNvim/CosmicNvim/issues/38

Should we find another way to load the mappings from lazy loaded plugins ? idk 🤷

**Comment by mattleong** [comment]
@maxime50 Ah thanks for pointing this out. Just pushed a fix for this so that it doesn't error out if that file isn't present. 

Lmk how it works out!

**Comment by mattleong** [comment]
Also, just as an FYI. There will be an update that refactors the configs a little bit and will cut down on the amount of different config files! Once that's released, there will only be two user config files to worry about. :D

**Comment by undeadbydawn** [comment]
The update resolved this error batch.
my other oustanding report persists
my issues are always reported immediately after running `git pull` and `:PackerSync`, so as up-to-date as remotely possible

**Comment by undeadbydawn** [comment]
Custom Settings:

---
config.lua contains

`local config = {}
config.theme = 'gruvbox'

return config`
---

editor.lua contains

`vim.o.wrap = true
vim.o.linebreak = true'
---

**Comment by maxime50** [comment]
@mattleong Yup it works great on my side now, thanks!
(sorry for the response delay😅)
