### ISSUE TITLE
Broken links in default mappings in README

### ISSUE THREAD

**Issue by gaiabeatrice** [CosmicNvim/CosmicNvim#47]
Hello! I love this project!
I'm just letting you know that all the links but the LSP one in the default mappings [section](https://github.com/CosmicNvim/CosmicNvim/blob/main/readme.md#-default-mappings) are broken.

**Comment by mattleong** [comment]
@gaiabeatrice I'm glad you're finding it useful!

And thank you! Just updated them :)
