### ISSUE TITLE
can't clone the repo

### ISSUE THREAD

**Issue by red-elka** [CosmicNvim/CosmicNvim#48]
update the readme
![Screenshot_20220207_130859](https://user-images.githubusercontent.com/95357302/152785803-16409831-fa96-4a3f-9bb9-441416fcc08d.png)

**Comment by mattleong** [comment]
Hm, are you able to clone other repos from Github using SSH? I would double check your SSH settings or try cloning with https.

**Comment by undeadbydawn** [comment]
> update the readme ![Screenshot_20220207_130859](https://user-images.githubusercontent.com/95357302/152785803-16409831-fa96-4a3f-9bb9-441416fcc08d.png)

I had the same problem.
You need to set up your git account with [ssh](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) and [gpg](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key) keys. Just follow the links and do as asked.
This may seem like a massive PITA but means you're fully set up to securely access all of GitHub, so is absolutely worth doing

**Comment by mattleong** [comment]
Closing as this isn't a Cosmic issue
