### ISSUE TITLE
Clone problem!

### ISSUE THREAD

**Issue by mafakheri** [CosmicNvim/CosmicNvim#55]
hi
i'm new to git and neovim and ....
why i can't clone the repo ?
i get some error about key fingerprint
can you help me what should i do.
sorry if it is bad Q.
tnx

**Comment by mattleong** [comment]
https://github.com/CosmicNvim/CosmicNvim/issues/48#issuecomment-1035572164

You likely need to set up your ssh keys. You can also clone via https if you want to avoid that
