### ISSUE TITLE
commands from nvim-lsp-ts-utils not available

### ISSUE THREAD

**Issue by krunicn** [CosmicNvim/CosmicNvim#56]
Hi, i have an issue with commands from nvim-lsp-ts-utils (TSLspOrganize etc.), seems like they are not set-up properly, when i try to call them it says "Not an editor command". 
However if i try to invoke them with `:lua require('nvim-lsp-ts-utils').organize_imports()` it does work. 
Has anyone else experienced this kind of issue?

**Comment by mattleong** [comment]
@krunicn Hm, they seem to be working for me. 

Can you provide me with more information?

- Are you on the latest NVIM nightly?
- Are you on the latest CosmicNvim?
- Do you have any custom configuration set up?

**Comment by krunicn** [comment]
Sure, yes i'm both on latest NVIM nightly, `NVIM v0.7.0-dev+1453-g8486c87e5` and CosmicVim.
I have some custom configuration but i've tried running without it as well, it's the same.

It looks to me like, for some reason, `define_commands` fn from nvim-lsp-ts-utils isn't called because if i run it manually with `lua require('nvim-lsp-ts-utils.define_commands')()` those commands become available.

**Comment by mattleong** [comment]
@krunicn Sorry for the late response. Did you ever get this resolved? I haven't seen similar issues appear.

**Comment by mattleong** [comment]
Unable to repro.

@krunicn if you still have this issue, please resubmit issue
