### ISSUE TITLE
Autocomplete Popup not Showing When Switching to Diffrent File

### ISSUE THREAD

**Issue by yoo** [CosmicNvim/CosmicNvim#62]
Hello, 
the autocomplete popup is not showing when I switch to a different (second) file. 

https://user-images.githubusercontent.com/1328109/166115370-de780e7d-2118-4138-8c3c-14b7b5bf8059.mp4

The autocomplete popup continues to work in the file I first opened when I switch back to it. 
I can bring up the autocompletion in the second file by pressing `<C-Space>`, but than `<Tab>` inserts the current selected match and doesn't select the next one.  
This happens to all files, it's not specific to Lua.
The method I use to switch the file `nvim-tree`, `telescope`, `:e <path>` doesn't matter either.  

I'm using Arch Linux with NeoVim 0.7.0 
```
$ nvim --verson
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
The video was taken on a fresh clone of Cosmic, no modifications to the config. I  deleted all old plugin/packer/cache folders I could find. 

I can reproduce it using the following Dockerfile:
```dockerfile
FROM archlinux:latest

RUN pacman -Syu --noconfirm

RUN set -ex ;\
    pacman -S --needed --noconfirm sudo ;\
    useradd builduser -m ;\
    passwd -d builduser ;\
    printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers

RUN set -ex ;\
    pacman -S --needed --noconfirm git base-devel ;\
    cd /tmp ;\
    sudo -u builduser bash -c 'git clone https://aur.archlinux.org/yay-bin.git ;\
    cd yay-bin ;\
    makepkg -si --noconfirm' ;\
    rm -rf yay-bin

RUN sudo -u builduser yay -S --noconfirm \
    neovim python-pynvim npm wget ruby fzf rg fd \
    nodejs-neovim ruby-neovim eslint_d prettierd \
    stylua nodejs-markdownlint-cli

RUN git clone https://github.com/CosmicNvim/CosmicNvim.git ~/.config/nvim

WORKDIR /root
CMD ["/usr/bin/bash"]
```

**Comment by pvamshi** [comment]
This is happening to me too, I just started trying. 
I heavily use <leader>ff and with that no file has autocomplete support.

**Comment by yoo** [comment]
@pvamshi you can change `lua/cosmic/plugins/nvim-cmp/init.lua:104`
form `    require('cmp').setup.buffer({ enabled = false })`
to `require('cmp').setup.buffer({ enabled = true })`. But i have no idea if this is the right way.

**Comment by mattleong** [comment]
I'm occasionally hitting this as well. Once it happens, you'll have to <TAB> for some reason before you see autocomplete suggestions. 

Definitely annoying. Investigating this as much as my free time permits me!

**Comment by mattleong** [comment]
@yoo @phatsk You two are gods among men! 

@phatsk your diagnosis is 💯. Thank you SO much for breaking that to light. 

Just pushed a fix :D
