### ISSUE TITLE
Silent error when requiring null_ls from inside user configuration

### ISSUE THREAD

**Issue by ettiernu** [CosmicNvim/CosmicNvim#63]
Seems to inconsistently fail, its very odd, but I've managed to solve it locally by changing the file:

`
lua/cosmic/lsp/providers/null_ls.lua
`
to reorder the requires:

```
local null_ls = require('null-ls')
local config = require('cosmic.core.user')
```

**Comment by ettiernu** [comment]
Unfortunately it has not.
Its very sporadic so I'm unable to tell exactly why, but sometimes as I'm opening nvim I can see the default 💫 on the corner instead of the symbol I defined in my cosmic.core.user, which is rather feature free:

```
-- Override Cosmic configuration options
local null_ls = require('null-ls')

local config = {
  auto_session = {},
  border = 'rounded',
  comment_nvim = {},
  cosmic_ui = {},
  diagnostic = {},
  gitsigns = {},
  lsp = {
    servers = {
      null_ls = {
        default_cosmic_sources = true,
        sources = {
          null_ls.builtins.formatting.lua_format.with({extra_args = {"--column-limit=120", "--indent-width=2"}}),
          null_ls.builtins.diagnostics.luacheck
        }
      }
    }
  },
  lsp_signature = {},
  luasnip = {},
  statusline = {main_icon = '🍄'},
  telescope = {},
  theme = 'tokyonight',
  todo_comments = {},
  treesitter = {},
  notify = {},
  nvim_cmp = {},
  nvim_tree = {},
  add_plugins = {
    'wakatime/vim-wakatime', -- Coding time
    'ggandor/lightspeed.nvim', -- Quick movement
    {
      'romgrk/barbar.nvim', -- Bar display
      requires = {'kyazdani42/nvim-web-devicons'}
    }
  },

  -- Disable plugins enabled by CosmicNvim
  disable_builtin_plugins = {
    --[[
    'auto-session',
    'nvim-cmp',
    'colorizer',
    'dashboard',
    'fugitive',
    'gitsigns',
    'comment-nvim',
    'nvim-tree',
    'galaxyline',
    'telescope',
    'terminal',
    'theme',
    'todo-comments',
    'treesitter',
    --]]
  }
}

return config
```

Nothing shows up on :messages
Just fails to load this file, which also means if I try to update it will attempt to remove the plugins in this list too.

**Comment by ettiernu** [comment]
Ah I should add I am running NVIM v0.8.0-dev on WSL2 ubuntu 22.04.
But this started happening with version 0.7.0 as well when I was compiling from stable.

**Comment by mattleong** [comment]
@ettiernu Think I just squashed this bug. Let me know if it's fixed for you!

**Comment by ettiernu** [comment]
Opened and closed nvim multiple times, always loaded my config. Think its fixed!
Thanks mattleong!

**Comment by ettiernu** [comment]
Seems like I was prematurely celebrating, it happened a few more times today as I opened up and closed instances of nvim..
Nothing on :messages still, just the tell-tale sign of the default cosmic nvim emoji

**Comment by mattleong** [comment]
@ettiernu has this been resolved for you? I haven't run into the issue since the PR merge.
