### ISSUE TITLE
Error with format on save

### ISSUE THREAD

**Issue by iver0** [CosmicNvim/CosmicNvim#64]
When saving a file, formatting fails with the following error:
```
Error detected while processing BufWritePre Autocommands for "*":
Error executing lua callback: .../iver/.config/nvim/lua/cosmic/lsp/providers/defaults.lua:33: attempt to call field 'format' (a nil value)
stack traceback:
```

**Comment by mattleong** [comment]
@iver0 What filetype is this failing on for you?

**Comment by iver0** [comment]
It's happening with all filetypes

**Comment by yoo** [comment]
It's possible to mitigate this by adding a nil check in front of the format call:
```lua
callback = function()
    if vim.lsp.buf.format == nil then
        return
    end
    vim.lsp.buf.format({
        timeout_ms = config.lsp.format_timeout,
    })
```
But this only feels like a workaround.

**Comment by iver0** [comment]
Yeah this is rather a workaround, format is always nil so it never gets called and so there's no way to format the file, not good

**Comment by mattleong** [comment]
@iver0 Please update to the latest nightly version of NVIM (v0.8.0)
