### ISSUE TITLE
Error when writing lua files.

### ISSUE THREAD

**Issue by ettiernu** [CosmicNvim/CosmicNvim#69]
Recent packer update has started triggering this error whenever I save a lua file.
Unsure about other file types.

```
Error detected while processing BufWritePre Autocommands for "*":
Error executing lua callback: vim/shared.lua:0: t: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'tbl_filter'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:205: in function 'format'
```

Also happened with current a vanilla pull from github, so its not something in my configuration.

**Comment by JohannWeging** [comment]
Hello, 
you need to install the NeoVim nightly >= 0.8 or use CosmicNvim  0.5.1

**Comment by mattleong** [comment]
@ettiernu Please update to the latest NVIM nightly
