### ISSUE TITLE
[Bug] Tab key in command line broken

### ISSUE THREAD

**Issue by vanarok** [CosmicNvim/CosmicNvim#72]
This happens after you have been working with vim for a while. Pressing the tab key enters this character. What plugin is involved?
![2022-06-09T23:49:45,560001621+04:00](https://user-images.githubusercontent.com/6105977/172932491-60c2e096-6708-4473-87c2-f55b2546517a.png)

**Comment by mattleong** [comment]
🤔 You can look at the `nvim-cmp` integration
