### ISSUE TITLE
[Bug] Catppuccin theme broken

### ISSUE THREAD

**Issue by vanarok** [CosmicNvim/CosmicNvim#73]
Cappuccin theme doesn't work, it looks like it has been recently updated, the method of get colors has been changed.

**Comment by davebrouwer1** [comment]
I found the gruvbox theme is broken as well, getting the following error amongst others : packer.nvim: Error running config for gruvbox: [string "..."]:0: Vim(colorscheme):E185: Cannot find color scheme 'gruvbo
x'

**Comment by mattleong** [comment]
@vanarok Do you know the latest commit that Cappuccin was working at? 

Either that, or I need to update the integration and then pin the theme version.

**Comment by mattleong** [comment]
@davebrouwer1 Same question?

**Comment by vanarok** [comment]
![2022-06-16T09:28:18,493641830+04:00](https://user-images.githubusercontent.com/6105977/173997985-62095bd9-4a74-498f-8eee-c25a324e9acd.png)

**Comment by vanarok** [comment]
> @davebrouwer1 Same question?
Is this what you need?
https://github.com/catppuccin/nvim/commit/773d339cbd307fe218cf7b3ea04eac26b345a3b7

**Comment by mattleong** [comment]
@vanarok fixed!

**Comment by mattleong** [comment]
@davebrouwer1 that error actually makes me think you didn't actually install the theme. Make sure to run `PackerSync`
