### ISSUE TITLE
Ignore config files of Neovim GUIs.

### ISSUE THREAD

**Issue by 2brownc** [CosmicNvim/CosmicNvim#77]
So GUIs for neovim like neovim-qt require config file like `ginit.vim` be present in the `~/.config/nvim` directory. So add them to the `.gitignore` file.

Example from AstroVim: https://github.com/AstroNvim/AstroNvim/blob/main/.gitignore

**Comment by mattleong** [comment]
@2brownc Could you add as a pull request? 🙏  I don't use GUI's for nvim

**Comment by prrockzed** [comment]
Hey, I added the file to the .gitignore
