### ISSUE TITLE
Wiki -> Configuration -> Click any of the listed links -> "You do not have permission to update this wiki."

### ISSUE THREAD

**Issue by zenVentzi** [CosmicNvim/CosmicNvim#83]
Links seem to be broken, or at least without access rights to the repo and lead back to the Wiki homepage. The image below is after you click any of the links in the Configuration wiki.

![image](https://user-images.githubusercontent.com/11378653/183295135-dcc044fb-51fb-4855-9f60-97913c2144cc.png)

**Comment by mattleong** [comment]
Fixed up broken links. Thanks!
