### ISSUE TITLE
null-ls.nvim config and noice.nvim error

### ISSUE THREAD

**Issue by ryannewcomer** [CosmicNvim/CosmicNvim#92]
![image](https://user-images.githubusercontent.com/88273136/211894328-483ccaf1-e5b7-4f38-8424-a10549c58eba.png)
 this was show when i open nvim

also, 
![image](https://user-images.githubusercontent.com/88273136/211894461-9d65edda-36ff-45db-aed8-eb20b3b9ac2a.png)
this was also show when i type command

**Comment by ryannewcomer** [comment]
pps: i am using kail linux on wsl

**Comment by mattleong** [comment]
@ryannewcomer Just pushed a fix for the first screenshot. Let me know if that is fixed for you now.

As for the second.. 

> this was also show when i type command

Can you provide a little better context here?

**Comment by andersonba** [comment]
Same here (about the second error)

See video:

https://user-images.githubusercontent.com/1501013/212217144-54923722-e194-4401-8d1b-1be7b6b479cd.mp4

**Comment by mattleong** [comment]
@andersonba Do you have a custom config? or is this a fresh install?

**Comment by andersonba** [comment]
@mattleong fresh install

It worked with the dev version of neovim (0.9)
