### ISSUE TITLE
my custom editor.lua isn't being considered

### ISSUE THREAD

**Issue by andersonba** [CosmicNvim/CosmicNvim#93]
It seems that my file is not being loaded, everything that I set there does not work, for example, the comma as `mapleader` 🤷‍♂️ 

```
⮩ cat ~/.config/nvim/lua/cosmic/config/editor.lua
local g = vim.g

g.mapleader = ','
```

Even copying the example files, the `mapleader` was not respected.

**Comment by mattleong** [comment]
https://github.com/CosmicNvim/CosmicNvim/pull/94

**Comment by mattleong** [comment]
@andersonba pushed a fix :D
