### ISSUE TITLE
Wrong require link found

### ISSUE THREAD

**Issue by IoT-master** [CosmicNvim/CosmicNvim#95]
nvim/lua/cosmic/core/init has an invalid require. To correct this error I removed cosmic.core.editor. I do see a cosmic.core.example.editor, but most people will not use it.

`local cosmic_modules = {
  'cosmic.core.editor',
  'cosmic.core.pluginsInit',
  'cosmic.core.commands',
  'cosmic.lsp',
  -- load mappings only after editor configs are loaded
  'cosmic.core.mappings',
}`

**Comment by mattleong** [comment]
Thanks! This should be fixed now 👍
