### ISSUE TITLE
Cosmic doesn't register/set leader key when first loading

### ISSUE THREAD

**Issue by hsheikhali1** [CosmicNvim/CosmicNvim#97]
The default keybinding for leader is `" "` however, my config should override that as soon as I load Cosmic but it doesn't. I have to open a file with the default leader then my leader mapping will be applied.

**Comment by andersonba** [comment]
Check your configuration file, if you have any errors in it (like lua runtime), the settings are disregarded. 

This happened to me, there was a code failure that ended up ignoring the file. A feedback on the UI would be welcome.

The change was introduced here:
https://github.com/CosmicNvim/CosmicNvim/commit/1e23745f643ca59629c7df961b8feed4704efd5c

**Comment by hsheikhali1** [comment]
I'd have to check again but I didn't see any runtime errors. Let me confirm and get back to you

**Comment by hsheikhali1** [comment]
@andersonba So, I was unable to figure out what was going on.. I also noticed that nvim-notify causes significant errors maybe thats why it wasn't working ? In my honest opinion, I think making nvim-notify optional would be nice.

**Comment by hsheikhali1** [comment]
Here is a very basic recording.. it shows that they keys I am pressing are in fact the new keybindings but it doesn't do anything until I use `space+ff`

Uploading Screen Recording 2023-02-25 at 2.41.56 PM.mov…

**Comment by hsheikhali1** [comment]
Here is a screengrab of me trying to use `,ff` to open telescope. There are no errors nothing but it doesn't trigger..

https://user-images.githubusercontent.com/14851850/221376565-aadea805-5f72-4efa-8482-12f81636bcfd.mov

**Comment by hsheikhali1** [comment]
Ohhhhhhhhhhhhh I figured out what's going on. Telescope is lazyloaded and is not being triggered with `,ff` the leader key is being set but I can't trigger telescope with it.. It's when I trigger it with `space ff` then it works with the new leader key.
